using System;
using System.Xml.Serialization;
using NamirialApiClient.Contracts.Base;

namespace NamirialApiClient.Contracts.Policies
{
    /// <summary>
    ///     Defines ad hoc policies configuration
    /// </summary>
    /// <remarks>
    ///     If the work step is not generated by hand but automatically generated by the work step Controller Ad hoc Policies
    ///     are specified
    /// </remarks>
    [Serializable]
    [XmlRoot("AdhocWorkstepConfiguration", Namespace = "", IsNullable = false)]
    public class AdhocPolicies : ServiceMessageBase<AdhocPolicies>
    {
        /// <summary>
        ///     Gets or Sets Allow Modifications After Signature
        /// </summary>
        [XmlElement("AllowModificationsAfterSignature", typeof (byte))]
        public byte AllowModificationsAfterSignature { get; set; }
    }
}